[package]
name = "practice-1"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
solana-client = "2.0.5"
solana-program = "2.0.5"
solana-sdk = "2.0.5"
thiserror = "1.0.63"
serde_json = "1.0.125"
anyhow = "1.0.86"
ed25519-dalek = "1.0.0"
