[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_approve = "C1cUvDnDKvN64HwAJp7Awfrb2LMiLQZywqfShFF73XcN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
