[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites = "6kvB6ULGVBxp9cx7a6o3zLx54rB6iHkZHJ7j2FMkSXrb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
